// 三国昆特牌卡牌数据（由 cards_254_v2_original_power.csv 生成）
var sanguo_card_dict = [
  {
    "id": 1,
    "name": "刘备",
    "orig": "弗尔泰斯特",
    "faction": "蜀汉",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "仁德：每局一次，弃牌堆复活1单位到手牌",
    "rarity": "leader",
    "filename": "刘备"
  },
  {
    "id": 2,
    "name": "刘禅",
    "orig": "拉多维德",
    "faction": "蜀汉",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "守成：每局一次消灭场上最高战力单位，获取点数",
    "rarity": "leader",
    "filename": "刘禅"
  },
  {
    "id": 3,
    "name": "曹操",
    "orig": "恩希尔",
    "faction": "曹魏",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "挟天子：每局一次牌库拿卧底放置对手半场",
    "rarity": "leader",
    "filename": "曹操"
  },
  {
    "id": 4,
    "name": "司马懿",
    "orig": "莫尔凡",
    "faction": "曹魏",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "隐忍：每局一次单位移出本局，下局回归",
    "rarity": "leader",
    "filename": "司马懿"
  },
  {
    "id": 5,
    "name": "孙权",
    "orig": "伊欧菲斯",
    "faction": "东吴",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "制衡江东：弃1手牌抽2张",
    "rarity": "leader",
    "filename": "孙权"
  },
  {
    "id": 6,
    "name": "张角",
    "orig": "艾瑞汀",
    "faction": "黄巾",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "苍天已死：单位战力翻倍，回合结束等量伤害",
    "rarity": "leader",
    "filename": "张角"
  },
  {
    "id": 7,
    "name": "袁绍",
    "orig": "克拉奇",
    "faction": "群雄(DLC)",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "会盟讨董：己方全体扣1，每扣1抽1牌",
    "rarity": "leader",
    "filename": "袁绍"
  },
  {
    "id": 8,
    "name": "马腾",
    "orig": "哈尔玛",
    "faction": "群雄(DLC)",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "西凉举义：墓地召唤死士上场",
    "rarity": "leader",
    "filename": "马腾"
  },
  {
    "id": 9,
    "name": "孟获",
    "orig": "赛瑞丝",
    "faction": "群雄(DLC)",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "南蛮再起：复活墓场南蛮单位",
    "rarity": "leader",
    "filename": "孟获"
  },
  {
    "id": 10,
    "name": "刘表",
    "orig": "斯凡瑞吉",
    "faction": "群雄(DLC)",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "荆襄固守：墓地1张单位移回手牌",
    "rarity": "leader",
    "filename": "刘表"
  },
  {
    "id": 11,
    "name": "袁术",
    "orig": "布兰王",
    "faction": "群雄(DLC)",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "僭号称帝：己方单位战力+1，对手抽1牌",
    "rarity": "leader",
    "filename": "袁术"
  },
  {
    "id": 12,
    "name": "公孙瓒",
    "orig": "克拉茨",
    "faction": "群雄(DLC)",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "白马义从：己方轻骑战力+2",
    "rarity": "leader",
    "filename": "公孙瓒"
  },
  {
    "id": 13,
    "name": "左慈",
    "orig": "镜子大师",
    "faction": "汉廷中立",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "幻术：复制对手上一张打出卡牌效果",
    "rarity": "leader",
    "filename": "左慈"
  },
  {
    "id": 14,
    "name": "貂蝉",
    "orig": "席安娜",
    "faction": "汉廷中立",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "离间：魅惑敌方单位变为己方卧底",
    "rarity": "leader",
    "filename": "貂蝉"
  },
  {
    "id": 15,
    "name": "汉献帝",
    "orig": "独角兽",
    "faction": "汉廷中立",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "衣带诏：每局一次，己方全体战力+1",
    "rarity": "leader",
    "filename": "汉献帝"
  },
  {
    "id": 16,
    "name": "皇甫嵩",
    "orig": "老巫妪",
    "faction": "汉廷中立",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "平定黄巾：对黄巾阵营单位造成2点伤害",
    "rarity": "leader",
    "filename": "皇甫嵩"
  },
  {
    "id": 17,
    "name": "朱隽",
    "orig": "牛",
    "faction": "汉廷中立",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "镇压黄巾：己方汉廷单位战力+1",
    "rarity": "leader",
    "filename": "朱隽"
  },
  {
    "id": 18,
    "name": "卢植",
    "orig": "欧吉尔德",
    "faction": "汉廷中立",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "大儒：每局一次，牌库拿1张谋士牌",
    "rarity": "leader",
    "filename": "卢植"
  },
  {
    "id": 19,
    "name": "蔡邕",
    "orig": "刚特·欧迪姆",
    "faction": "汉廷中立",
    "deck": "leader",
    "type": "领袖",
    "row": "",
    "strength": 0,
    "ability": "leader",
    "keyword": "博学：每局一次，查看对手手牌",
    "rarity": "leader",
    "filename": "蔡邕"
  },
  {
    "id": 20,
    "name": "关羽",
    "orig": "维瑟米尔",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "金卡",
    "row": "close",
    "strength": 12,
    "ability": "hero",
    "keyword": "猛将【T1第6】蜀汉战力最高，万军斩颜良",
    "rarity": "gold",
    "filename": "关羽"
  },
  {
    "id": 21,
    "name": "张飞",
    "orig": "弗农·罗契",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "金卡",
    "row": "close",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【T1第5】百回合硬刚吕布",
    "rarity": "gold",
    "filename": "张飞"
  },
  {
    "id": 22,
    "name": "魏延",
    "orig": "伊斯特拉德·帝森",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "金卡",
    "row": "close",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【T2第20】蜀汉后期头号猛将",
    "rarity": "gold",
    "filename": "魏延"
  },
  {
    "id": 23,
    "name": "赵云",
    "orig": "约翰·纳塔利斯",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "金卡",
    "row": "close",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将、灵活【T1第2】长坂坡七进七出",
    "rarity": "gold",
    "filename": "赵云"
  },
  {
    "id": 24,
    "name": "马超",
    "orig": "狮鹫",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "金卡",
    "row": "close",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将、灵活【T1第4】潼关杀曹操割须弃袍",
    "rarity": "gold",
    "filename": "马超"
  },
  {
    "id": 25,
    "name": "诸葛亮",
    "orig": "菲丽芭·艾哈特",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "金卡",
    "row": "ranged",
    "strength": 10,
    "ability": "hero medic",
    "keyword": "猛将、归阵【S档第1】演义智力天花板",
    "rarity": "gold",
    "filename": "诸葛亮"
  },
  {
    "id": 26,
    "name": "黄忠",
    "orig": "迪杰斯特拉",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "金卡",
    "row": "ranged",
    "strength": 9,
    "ability": "hero",
    "keyword": "猛将、烽火燎原【T1第10】百步穿杨，定军山斩夏侯渊",
    "rarity": "gold",
    "filename": "黄忠"
  },
  {
    "id": 27,
    "name": "典韦",
    "orig": "梅诺·寇赫伦",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "金卡",
    "row": "close",
    "strength": 12,
    "ability": "hero",
    "keyword": "猛将【T1第3】宛城死战",
    "rarity": "gold",
    "filename": "典韦"
  },
  {
    "id": 28,
    "name": "贾诩",
    "orig": "雷吉斯",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "金卡",
    "row": "ranged",
    "strength": 11,
    "ability": "hero medic",
    "keyword": "猛将、归阵【S档第3】算无遗策",
    "rarity": "gold",
    "filename": "贾诩"
  },
  {
    "id": 29,
    "name": "张辽",
    "orig": "古雷特的雷索",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "金卡",
    "row": "close",
    "strength": 10,
    "ability": "hero spy",
    "keyword": "猛将、卧底【T2第18】威震逍遥津",
    "rarity": "gold",
    "filename": "张辽"
  },
  {
    "id": 30,
    "name": "荀彧",
    "orig": "提伯·艾格布拉杰",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "金卡",
    "row": "ranged",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【S档第4】挟天子顶层战略",
    "rarity": "gold",
    "filename": "荀彧"
  },
  {
    "id": 31,
    "name": "许褚",
    "orig": "兰伯特",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "金卡",
    "row": "close",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【T1第7】虎痴",
    "rarity": "gold",
    "filename": "许褚"
  },
  {
    "id": 32,
    "name": "程昱",
    "orig": "莫尔凡·符里斯",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "金卡",
    "row": "ranged",
    "strength": 9,
    "ability": "hero spy",
    "keyword": "猛将、卧底【A档第10】十面埋伏",
    "rarity": "gold",
    "filename": "程昱"
  },
  {
    "id": 33,
    "name": "周瑜",
    "orig": "埃丝涅",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "金卡",
    "row": "ranged",
    "strength": 12,
    "ability": "hero",
    "keyword": "猛将【A档第7】赤壁火攻",
    "rarity": "gold",
    "filename": "周瑜"
  },
  {
    "id": 34,
    "name": "太史慈",
    "orig": "伊森格林",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "金卡",
    "row": "ranged",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【T2第14】神亭岭战孙策",
    "rarity": "gold",
    "filename": "太史慈"
  },
  {
    "id": 35,
    "name": "甘宁",
    "orig": "萨琪亚",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "金卡",
    "row": "agile",
    "strength": 10,
    "ability": "hero agile",
    "keyword": "猛将、灵活、伏击【T2第21】百骑劫曹营",
    "rarity": "gold",
    "filename": "甘宁"
  },
  {
    "id": 36,
    "name": "孙策",
    "orig": "伊欧菲斯",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "金卡",
    "row": "close",
    "strength": 9,
    "ability": "hero",
    "keyword": "猛将、灵活【T2第13】小霸王",
    "rarity": "gold",
    "filename": "孙策"
  },
  {
    "id": 37,
    "name": "黄巾力士统领",
    "orig": "巨章鱼怪",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "金卡",
    "row": "close",
    "strength": 11,
    "ability": "hero",
    "keyword": "猛将【精英】黄巾精锐统领",
    "rarity": "gold",
    "filename": "黄巾力士统领"
  },
  {
    "id": 38,
    "name": "张宝",
    "orig": "战灵",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "金卡",
    "row": "ranged",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【一流】地公将军",
    "rarity": "gold",
    "filename": "张宝"
  },
  {
    "id": 39,
    "name": "黄巾巫王",
    "orig": "鹿首精",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "金卡",
    "row": "ranged",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【精英】黄巾法术领袖",
    "rarity": "gold",
    "filename": "黄巾巫王"
  },
  {
    "id": 40,
    "name": "波才",
    "orig": "伊勒瑞斯",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "金卡",
    "row": "close",
    "strength": 9,
    "ability": "hero",
    "keyword": "猛将【一流】黄巾大将",
    "rarity": "gold",
    "filename": "波才"
  },
  {
    "id": 41,
    "name": "颜良",
    "orig": "哈尔玛",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "金卡",
    "row": "close",
    "strength": 11,
    "ability": "hero",
    "keyword": "猛将【T1第8】二十合败徐晃",
    "rarity": "gold",
    "filename": "颜良"
  },
  {
    "id": 42,
    "name": "文丑",
    "orig": "汉姆多尔",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "金卡",
    "row": "close",
    "strength": 11,
    "ability": "hero muster",
    "keyword": "猛将、死士【T1第9】击退张辽徐晃",
    "rarity": "gold",
    "filename": "文丑"
  },
  {
    "id": 43,
    "name": "祝融",
    "orig": "凯瑞丝",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "金卡",
    "row": "ranged",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【一流】南蛮第一女将",
    "rarity": "gold",
    "filename": "祝融"
  },
  {
    "id": 44,
    "name": "华雄",
    "orig": "尔米亚",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "金卡",
    "row": "close",
    "strength": 9,
    "ability": "hero bond",
    "keyword": "猛将、同袍呼应【T2第22】威震关东",
    "rarity": "gold",
    "filename": "华雄"
  },
  {
    "id": 45,
    "name": "吕布",
    "orig": "杰洛特",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "金卡",
    "row": "close",
    "strength": 15,
    "ability": "hero",
    "keyword": "猛将【T0天花板】虎牢关独战刘关张",
    "rarity": "gold",
    "filename": "吕布"
  },
  {
    "id": 46,
    "name": "董卓",
    "orig": "希里",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "金卡",
    "row": "close",
    "strength": 14,
    "ability": "hero",
    "keyword": "猛将【权臣】挟天子令诸侯",
    "rarity": "gold",
    "filename": "董卓"
  },
  {
    "id": 47,
    "name": "李儒",
    "orig": "叶奈法",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "金卡",
    "row": "ranged",
    "strength": 12,
    "ability": "hero medic",
    "keyword": "猛将、归阵【A档第12】董卓第一谋主",
    "rarity": "gold",
    "filename": "李儒"
  },
  {
    "id": 48,
    "name": "高顺",
    "orig": "特莉丝",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "金卡",
    "row": "close",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【吕布八健将之首】陷阵营统领",
    "rarity": "gold",
    "filename": "高顺"
  },
  {
    "id": 49,
    "name": "于吉",
    "orig": "神秘的精灵",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "金卡",
    "row": "ranged",
    "strength": 10,
    "ability": "hero",
    "keyword": "猛将【术士】太平道，符水治病",
    "rarity": "gold",
    "filename": "于吉"
  },
  {
    "id": 50,
    "name": "说书人",
    "orig": "丹德里恩",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "金卡",
    "row": "ranged",
    "strength": 9,
    "ability": "hero morale",
    "keyword": "猛将、士气大振【中立】",
    "rarity": "gold",
    "filename": "说书人"
  },
  {
    "id": 51,
    "name": "白耳骑兵",
    "orig": "骑士",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】刘备亲卫",
    "rarity": "silver",
    "filename": "白耳骑兵"
  },
  {
    "id": 52,
    "name": "蜀汉军医",
    "orig": "医师",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 5,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "silver",
    "filename": "蜀汉军医"
  },
  {
    "id": 53,
    "name": "无当飞军",
    "orig": "弩手",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "ranged",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】南中精锐",
    "rarity": "silver",
    "filename": "无当飞军"
  },
  {
    "id": 54,
    "name": "蜀地斥候",
    "orig": "斥候",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "侦查【辅助】",
    "rarity": "silver",
    "filename": "蜀地斥候"
  },
  {
    "id": 55,
    "name": "蜀地投石机",
    "orig": "投石机",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "蜀地投石机"
  },
  {
    "id": 56,
    "name": "蜀攻城匠",
    "orig": "科德温攻城专家",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "siege",
    "strength": 4,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "蜀攻城匠"
  },
  {
    "id": 57,
    "name": "蜀精锐步曲",
    "orig": "蓝衣铁卫突击队",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 5,
    "ability": "morale",
    "keyword": "士气大振【精锐】",
    "rarity": "silver",
    "filename": "蜀精锐步曲"
  },
  {
    "id": 58,
    "name": "蜀郡征夫",
    "orig": "可怜的步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "蜀郡征夫"
  },
  {
    "id": 59,
    "name": "蜀地乡勇",
    "orig": "瑞达尼亚步军",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 1,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "蜀地乡勇"
  },
  {
    "id": 60,
    "name": "蜀边屯兵",
    "orig": "泰莫利亚步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "蜀边屯兵"
  },
  {
    "id": 61,
    "name": "蜀戍卒",
    "orig": "科德温步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "蜀戍卒"
  },
  {
    "id": 62,
    "name": "蜀汉弓手",
    "orig": "弓箭手",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "蜀汉弓手"
  },
  {
    "id": 63,
    "name": "蜀汉轻骑",
    "orig": "轻骑兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "无【普通】",
    "rarity": "silver",
    "filename": "蜀汉轻骑"
  },
  {
    "id": 64,
    "name": "蜀汉重步",
    "orig": "重骑兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "close",
    "strength": 4,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "silver",
    "filename": "蜀汉重步"
  },
  {
    "id": 65,
    "name": "庞统",
    "orig": "法师学徒",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "银卡",
    "row": "ranged",
    "strength": 2,
    "ability": "morale",
    "keyword": "士气大振【A档第8】凤雏，与卧龙齐名，连环计",
    "rarity": "silver",
    "filename": "庞统"
  },
  {
    "id": 66,
    "name": "虎豹骑",
    "orig": "尼弗迦德士兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】曹操亲骑",
    "rarity": "silver",
    "filename": "虎豹骑"
  },
  {
    "id": 67,
    "name": "郭嘉",
    "orig": "尼弗迦德法师",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "ranged",
    "strength": 5,
    "ability": "spy",
    "keyword": "卧底【A档第5】鬼才，十胜十败论",
    "rarity": "silver",
    "filename": "郭嘉"
  },
  {
    "id": 68,
    "name": "曹魏军医",
    "orig": "尼弗迦德医师",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "close",
    "strength": 4,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "silver",
    "filename": "曹魏军医"
  },
  {
    "id": 69,
    "name": "曹魏探马",
    "orig": "尼弗迦德斥候",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "侦查【辅助】",
    "rarity": "silver",
    "filename": "曹魏探马"
  },
  {
    "id": 70,
    "name": "曹魏冲车",
    "orig": "尼弗迦德投石机",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "曹魏冲车"
  },
  {
    "id": 71,
    "name": "破损冲车",
    "orig": "腐烂的射石机",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "siege",
    "strength": 3,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "破损冲车"
  },
  {
    "id": 72,
    "name": "曹魏死士",
    "orig": "弗林姆德",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "close",
    "strength": 2,
    "ability": "",
    "keyword": "殉战【精英】",
    "rarity": "silver",
    "filename": "曹魏死士"
  },
  {
    "id": 73,
    "name": "曹魏细作统领",
    "orig": "希尔拉德",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "ranged",
    "strength": 6,
    "ability": "spy",
    "keyword": "卧底【精英】",
    "rarity": "silver",
    "filename": "曹魏细作统领"
  },
  {
    "id": 74,
    "name": "青州步兵",
    "orig": "尼弗迦德步兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "close",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "青州步兵"
  },
  {
    "id": 75,
    "name": "曹魏弓兵",
    "orig": "尼弗迦德弓箭手",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "曹魏弓兵"
  },
  {
    "id": 76,
    "name": "曹魏轻骑",
    "orig": "尼弗迦德轻骑兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "无【普通】",
    "rarity": "silver",
    "filename": "曹魏轻骑"
  },
  {
    "id": 77,
    "name": "曹魏重骑",
    "orig": "尼弗迦德重骑兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "close",
    "strength": 4,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "silver",
    "filename": "曹魏重骑"
  },
  {
    "id": 78,
    "name": "曹魏细作",
    "orig": "尼弗迦德法师学徒",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "ranged",
    "strength": 2,
    "ability": "spy",
    "keyword": "卧底【普通】",
    "rarity": "silver",
    "filename": "曹魏细作"
  },
  {
    "id": 79,
    "name": "曹魏弩卒",
    "orig": "尼弗迦德弩手",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "ranged",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "曹魏弩卒"
  },
  {
    "id": 80,
    "name": "于禁",
    "orig": "黑步兵弓箭手",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "银卡",
    "row": "ranged",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【一流】治军严谨",
    "rarity": "silver",
    "filename": "于禁"
  },
  {
    "id": 81,
    "name": "锦帆游击",
    "orig": "精灵游击兵",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "agile",
    "strength": 5,
    "ability": "agile",
    "keyword": "伏击【精锐】甘宁锦帆军",
    "rarity": "silver",
    "filename": "锦帆游击"
  },
  {
    "id": 82,
    "name": "江东水军",
    "orig": "矮人战士",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "silver",
    "filename": "江东水军"
  },
  {
    "id": 83,
    "name": "陆逊",
    "orig": "精灵法师",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "agile",
    "strength": 5,
    "ability": "agile",
    "keyword": "伏击【A档第6】火烧连营",
    "rarity": "silver",
    "filename": "陆逊"
  },
  {
    "id": 84,
    "name": "东吴军医",
    "orig": "矮人医师",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "close",
    "strength": 4,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "silver",
    "filename": "东吴军医"
  },
  {
    "id": 85,
    "name": "东吴楼船器械",
    "orig": "矮人投石机",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "东吴楼船器械"
  },
  {
    "id": 86,
    "name": "江东弩手",
    "orig": "多尔布雷坦纳弓箭手",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "agile",
    "strength": 4,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "silver",
    "filename": "江东弩手"
  },
  {
    "id": 87,
    "name": "江东游医",
    "orig": "私枭医生",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "close",
    "strength": 3,
    "ability": "medic",
    "keyword": "归阵【普通】",
    "rarity": "silver",
    "filename": "江东游医"
  },
  {
    "id": 88,
    "name": "江东宿卫",
    "orig": "维里赫德旅老兵",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "close",
    "strength": 5,
    "ability": "morale",
    "keyword": "士气大振【精锐】",
    "rarity": "silver",
    "filename": "江东宿卫"
  },
  {
    "id": 89,
    "name": "江东新兵",
    "orig": "维里赫德旅见习生",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "agile",
    "strength": 3,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "silver",
    "filename": "江东新兵"
  },
  {
    "id": 90,
    "name": "山越兵",
    "orig": "精灵战士",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "agile",
    "strength": 3,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "silver",
    "filename": "山越兵"
  },
  {
    "id": 91,
    "name": "东吴弓卒",
    "orig": "精灵弓箭手",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "agile",
    "strength": 3,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "silver",
    "filename": "东吴弓卒"
  },
  {
    "id": 92,
    "name": "东吴弩手",
    "orig": "矮人弓箭手",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "东吴弩手"
  },
  {
    "id": 93,
    "name": "凌统",
    "orig": "多尔布雷坦纳侦察兵",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "银卡",
    "row": "agile",
    "strength": 2,
    "ability": "agile",
    "keyword": "伏击【一流】合肥救主",
    "rarity": "silver",
    "filename": "凌统"
  },
  {
    "id": 94,
    "name": "黄巾渠帅",
    "orig": "食尸鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "",
    "keyword": "殉战【精英】",
    "rarity": "silver",
    "filename": "黄巾渠帅"
  },
  {
    "id": 95,
    "name": "黄巾水卒",
    "orig": "水鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "agile",
    "strength": 4,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "silver",
    "filename": "黄巾水卒"
  },
  {
    "id": 96,
    "name": "黄巾力士",
    "orig": "沼泽怪",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "silver",
    "filename": "黄巾力士"
  },
  {
    "id": 97,
    "name": "黄巾死囚",
    "orig": "墓穴食尸妖",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 4,
    "ability": "",
    "keyword": "殉战【普通】",
    "rarity": "silver",
    "filename": "黄巾死囚"
  },
  {
    "id": 98,
    "name": "黄巾巫祝",
    "orig": "吸血鬼：吸血女妖",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "ranged",
    "strength": 5,
    "ability": "muster",
    "keyword": "死士【辅助】",
    "rarity": "silver",
    "filename": "黄巾巫祝"
  },
  {
    "id": 99,
    "name": "黄巾狂徒",
    "orig": "吸血鬼：蝠翼妖",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 4,
    "ability": "muster",
    "keyword": "聚将【普通】",
    "rarity": "silver",
    "filename": "黄巾狂徒"
  },
  {
    "id": 100,
    "name": "黄巾悍匪",
    "orig": "吸血鬼：卡塔坎",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "silver",
    "filename": "黄巾悍匪"
  },
  {
    "id": 101,
    "name": "黄巾游骑",
    "orig": "孽鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 2,
    "ability": "muster",
    "keyword": "聚将【普通】",
    "rarity": "silver",
    "filename": "黄巾游骑"
  },
  {
    "id": 102,
    "name": "黄巾小帅",
    "orig": "孽鬼战士",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 3,
    "ability": "muster",
    "keyword": "聚将【普通】",
    "rarity": "silver",
    "filename": "黄巾小帅"
  },
  {
    "id": 103,
    "name": "黄巾山砦",
    "orig": "地元素",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "siege",
    "strength": 5,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "黄巾山砦"
  },
  {
    "id": 104,
    "name": "黄巾流民",
    "orig": "腐食魔",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 2,
    "ability": "",
    "keyword": "殉战【普通】",
    "rarity": "silver",
    "filename": "黄巾流民"
  },
  {
    "id": 105,
    "name": "黄巾步兵",
    "orig": "食尸鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "close",
    "strength": 3,
    "ability": "muster",
    "keyword": "死士【普通】",
    "rarity": "silver",
    "filename": "黄巾步兵"
  },
  {
    "id": 106,
    "name": "黄巾河兵",
    "orig": "水鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "agile",
    "strength": 2,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "silver",
    "filename": "黄巾河兵"
  },
  {
    "id": 107,
    "name": "黄巾哨探",
    "orig": "食腐鸟",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "agile",
    "strength": 1,
    "ability": "",
    "keyword": "无【普通】",
    "rarity": "silver",
    "filename": "黄巾哨探"
  },
  {
    "id": 108,
    "name": "黄巾砦守",
    "orig": "石像鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "银卡",
    "row": "siege",
    "strength": 3,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "黄巾砦守"
  },
  {
    "id": 109,
    "name": "南蛮死士",
    "orig": "狂战士",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "silver",
    "filename": "南蛮死士"
  },
  {
    "id": 110,
    "name": "南蛮蛮兵",
    "orig": "盾女",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "close",
    "strength": 5,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "silver",
    "filename": "南蛮蛮兵"
  },
  {
    "id": 111,
    "name": "羌胡猎手",
    "orig": "猎人",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "ranged",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "羌胡猎手"
  },
  {
    "id": 112,
    "name": "南蛮巫祝",
    "orig": "萨满",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "ranged",
    "strength": 4,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "silver",
    "filename": "南蛮巫祝"
  },
  {
    "id": 113,
    "name": "诸侯斥候",
    "orig": "史凯利格斥候",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "侦查【辅助】",
    "rarity": "silver",
    "filename": "诸侯斥候"
  },
  {
    "id": 114,
    "name": "诸侯攻城冲车",
    "orig": "史凯利格投石机",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "诸侯攻城冲车"
  },
  {
    "id": 115,
    "name": "南蛮勇士",
    "orig": "安·克莱特家族战士",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精英】",
    "rarity": "silver",
    "filename": "南蛮勇士"
  },
  {
    "id": 116,
    "name": "羌弓手",
    "orig": "布罗克瓦家族弓箭手",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "ranged",
    "strength": 6,
    "ability": "",
    "keyword": "无【精英】",
    "rarity": "silver",
    "filename": "羌弓手"
  },
  {
    "id": 117,
    "name": "蛮部劫掠者",
    "orig": "迪门家族海盗",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "agile",
    "strength": 5,
    "ability": "",
    "keyword": "殉战【普通】",
    "rarity": "silver",
    "filename": "蛮部劫掠者"
  },
  {
    "id": 118,
    "name": "南蛮盾卫",
    "orig": "德拉蒙家族盾女",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "close",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【精英】",
    "rarity": "silver",
    "filename": "南蛮盾卫"
  },
  {
    "id": 119,
    "name": "诸侯说客",
    "orig": "海梅家族吟游诗人",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "ranged",
    "strength": 4,
    "ability": "morale",
    "keyword": "士气大振【辅助】",
    "rarity": "silver",
    "filename": "诸侯说客"
  },
  {
    "id": 120,
    "name": "诸侯工匠",
    "orig": "托达罗赫家族军械师",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "siege",
    "strength": 4,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "silver",
    "filename": "诸侯工匠"
  },
  {
    "id": 121,
    "name": "蛮部快船",
    "orig": "轻型大艇",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "agile",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【器械】",
    "rarity": "silver",
    "filename": "蛮部快船"
  },
  {
    "id": 122,
    "name": "蛮部战舰",
    "orig": "战型大艇",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "agile",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【器械】",
    "rarity": "silver",
    "filename": "蛮部战舰"
  },
  {
    "id": 123,
    "name": "南蛮巨兽",
    "orig": "奥拉夫",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "close",
    "strength": 4,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "silver",
    "filename": "南蛮巨兽"
  },
  {
    "id": 124,
    "name": "南蛮酋长",
    "orig": "德拉伊格",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "close",
    "strength": 5,
    "ability": "",
    "keyword": "殉战【精英】",
    "rarity": "silver",
    "filename": "南蛮酋长"
  },
  {
    "id": 125,
    "name": "马岱",
    "orig": "霍尔格",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【西凉派系】斩杀魏延",
    "rarity": "silver",
    "filename": "马岱"
  },
  {
    "id": 126,
    "name": "沮授",
    "orig": "奥拉夫",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "ranged",
    "strength": 4,
    "ability": "medic",
    "keyword": "归阵【B档第15】最早提出迎天子",
    "rarity": "silver",
    "filename": "沮授"
  },
  {
    "id": 127,
    "name": "田丰",
    "orig": "德拉伊格",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "ranged",
    "strength": 5,
    "ability": "",
    "keyword": "殉战【B档第16】劝袁绍勿急战",
    "rarity": "silver",
    "filename": "田丰"
  },
  {
    "id": 128,
    "name": "陈宫",
    "orig": "坎毕",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "银卡",
    "row": "ranged",
    "strength": 0,
    "ability": "",
    "keyword": "殉战【A档第13】多次算计曹操",
    "rarity": "silver",
    "filename": "陈宫"
  },
  {
    "id": 129,
    "name": "汉献帝",
    "orig": "独角兽",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "ranged",
    "strength": 5,
    "ability": "purify",
    "keyword": "净化【特殊】汉室天子",
    "rarity": "silver",
    "filename": "汉献帝"
  },
  {
    "id": 130,
    "name": "华佗",
    "orig": "老巫妪",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "ranged",
    "strength": 10,
    "ability": "medic",
    "keyword": "归阵【神医】外科圣手",
    "rarity": "silver",
    "filename": "华佗"
  },
  {
    "id": 131,
    "name": "牛来",
    "orig": "牛",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "close",
    "strength": 1,
    "ability": "",
    "keyword": "无【梗】电影《牛来》",
    "rarity": "silver",
    "filename": "牛来"
  },
  {
    "id": 132,
    "name": "臧霸",
    "orig": "欧吉尔德",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "close",
    "strength": 8,
    "ability": "hero",
    "keyword": "猛将【吕布八健将】后降曹，封良成侯",
    "rarity": "silver",
    "filename": "臧霸"
  },
  {
    "id": 133,
    "name": "幻术黑影",
    "orig": "刚特·欧迪姆黑暗",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "ranged",
    "strength": 0,
    "ability": "purify",
    "keyword": "净化【特殊】",
    "rarity": "silver",
    "filename": "幻术黑影"
  },
  {
    "id": 134,
    "name": "汉室流民",
    "orig": "农民",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "close",
    "strength": 1,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "汉室流民"
  },
  {
    "id": 135,
    "name": "汉室民兵",
    "orig": "民兵",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "silver",
    "filename": "汉室民兵"
  },
  {
    "id": 136,
    "name": "曹性",
    "orig": "汉廷弓箭手",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "银卡",
    "row": "ranged",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【吕布八健将】射瞎夏侯惇左眼",
    "rarity": "silver",
    "filename": "曹性"
  },
  {
    "id": 137,
    "name": "蜀汉步兵",
    "orig": "步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "蜀汉步兵"
  },
  {
    "id": 138,
    "name": "蜀汉弓手",
    "orig": "弓箭手",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "蜀汉弓手"
  },
  {
    "id": 139,
    "name": "蜀汉轻骑",
    "orig": "轻骑兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "无【普通】",
    "rarity": "bronze",
    "filename": "蜀汉轻骑"
  },
  {
    "id": 140,
    "name": "蜀汉重步",
    "orig": "重骑兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 4,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "bronze",
    "filename": "蜀汉重步"
  },
  {
    "id": 141,
    "name": "蜀地幕僚",
    "orig": "法师学徒",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "ranged",
    "strength": 2,
    "ability": "morale",
    "keyword": "士气大振【普通】",
    "rarity": "bronze",
    "filename": "蜀地幕僚"
  },
  {
    "id": 142,
    "name": "蜀地乡勇",
    "orig": "瑞达尼亚步军",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 1,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "蜀地乡勇"
  },
  {
    "id": 143,
    "name": "蜀边屯兵",
    "orig": "泰莫利亚步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "蜀边屯兵"
  },
  {
    "id": 144,
    "name": "蜀戍卒",
    "orig": "科德温步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "蜀戍卒"
  },
  {
    "id": 145,
    "name": "蜀郡征夫",
    "orig": "可怜的步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "蜀郡征夫"
  },
  {
    "id": 146,
    "name": "蜀精锐步曲",
    "orig": "蓝衣铁卫突击队",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 5,
    "ability": "morale",
    "keyword": "士气大振【精锐】",
    "rarity": "bronze",
    "filename": "蜀精锐步曲"
  },
  {
    "id": 147,
    "name": "无当飞军",
    "orig": "弩手",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "ranged",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "bronze",
    "filename": "无当飞军"
  },
  {
    "id": 148,
    "name": "白耳骑兵",
    "orig": "骑士",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "bronze",
    "filename": "白耳骑兵"
  },
  {
    "id": 149,
    "name": "蜀地投石机",
    "orig": "投石机",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "蜀地投石机"
  },
  {
    "id": 150,
    "name": "蜀攻城匠",
    "orig": "科德温攻城专家",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "siege",
    "strength": 4,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "蜀攻城匠"
  },
  {
    "id": 151,
    "name": "蜀汉军医",
    "orig": "医师",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 5,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "bronze",
    "filename": "蜀汉军医"
  },
  {
    "id": 152,
    "name": "蜀地斥候",
    "orig": "斥候",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "侦查【辅助】",
    "rarity": "bronze",
    "filename": "蜀地斥候"
  },
  {
    "id": 153,
    "name": "蜀汉连弩手",
    "orig": "弓箭手",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "蜀汉连弩手"
  },
  {
    "id": 154,
    "name": "蜀汉盾兵",
    "orig": "步兵",
    "faction": "蜀汉",
    "deck": "shuhan",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "bronze",
    "filename": "蜀汉盾兵"
  },
  {
    "id": 155,
    "name": "青州步兵",
    "orig": "尼弗迦德步兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "青州步兵"
  },
  {
    "id": 156,
    "name": "曹魏弓兵",
    "orig": "尼弗迦德弓箭手",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "曹魏弓兵"
  },
  {
    "id": 157,
    "name": "曹魏轻骑",
    "orig": "尼弗迦德轻骑兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "无【普通】",
    "rarity": "bronze",
    "filename": "曹魏轻骑"
  },
  {
    "id": 158,
    "name": "曹魏重骑",
    "orig": "尼弗迦德重骑兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "close",
    "strength": 4,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "bronze",
    "filename": "曹魏重骑"
  },
  {
    "id": 159,
    "name": "曹魏细作",
    "orig": "尼弗迦德法师学徒",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "ranged",
    "strength": 2,
    "ability": "spy",
    "keyword": "卧底【普通】",
    "rarity": "bronze",
    "filename": "曹魏细作"
  },
  {
    "id": 160,
    "name": "曹魏弩卒",
    "orig": "尼弗迦德弩手",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "ranged",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "曹魏弩卒"
  },
  {
    "id": 161,
    "name": "虎豹骑",
    "orig": "尼弗迦德士兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "bronze",
    "filename": "虎豹骑"
  },
  {
    "id": 162,
    "name": "曹魏谋臣",
    "orig": "尼弗迦德法师",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "ranged",
    "strength": 5,
    "ability": "spy",
    "keyword": "卧底【辅助】",
    "rarity": "bronze",
    "filename": "曹魏谋臣"
  },
  {
    "id": 163,
    "name": "曹魏军医",
    "orig": "尼弗迦德医师",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "close",
    "strength": 4,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "bronze",
    "filename": "曹魏军医"
  },
  {
    "id": 164,
    "name": "曹魏探马",
    "orig": "尼弗迦德斥候",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "侦查【辅助】",
    "rarity": "bronze",
    "filename": "曹魏探马"
  },
  {
    "id": 165,
    "name": "曹魏冲车",
    "orig": "尼弗迦德投石机",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "曹魏冲车"
  },
  {
    "id": 166,
    "name": "破损冲车",
    "orig": "腐烂的射石机",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "siege",
    "strength": 3,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "破损冲车"
  },
  {
    "id": 167,
    "name": "曹魏死士",
    "orig": "弗林姆德",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "",
    "keyword": "殉战【精英】",
    "rarity": "bronze",
    "filename": "曹魏死士"
  },
  {
    "id": 168,
    "name": "曹魏细作统领",
    "orig": "希尔拉德",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "ranged",
    "strength": 6,
    "ability": "spy",
    "keyword": "卧底【精英】",
    "rarity": "bronze",
    "filename": "曹魏细作统领"
  },
  {
    "id": 169,
    "name": "曹魏宿卫弩手",
    "orig": "黑步兵弓箭手",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "ranged",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "bronze",
    "filename": "曹魏宿卫弩手"
  },
  {
    "id": 170,
    "name": "兖州兵",
    "orig": "尼弗迦德步兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "兖州兵"
  },
  {
    "id": 171,
    "name": "许昌弓手",
    "orig": "尼弗迦德弓箭手",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "许昌弓手"
  },
  {
    "id": 172,
    "name": "虎豹轻骑",
    "orig": "尼弗迦德轻骑兵",
    "faction": "曹魏",
    "deck": "caowei",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "无【普通】",
    "rarity": "bronze",
    "filename": "虎豹轻骑"
  },
  {
    "id": 173,
    "name": "山越兵",
    "orig": "精灵战士",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 3,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "山越兵"
  },
  {
    "id": 174,
    "name": "东吴弓卒",
    "orig": "精灵弓箭手",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 3,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "东吴弓卒"
  },
  {
    "id": 175,
    "name": "江东步卒",
    "orig": "矮人战士",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "江东步卒"
  },
  {
    "id": 176,
    "name": "东吴弩手",
    "orig": "矮人弓箭手",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "东吴弩手"
  },
  {
    "id": 177,
    "name": "江东探卒",
    "orig": "多尔布雷坦纳侦察兵",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 2,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "江东探卒"
  },
  {
    "id": 178,
    "name": "吴郡弓手",
    "orig": "维里赫德旅弓手",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 2,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "吴郡弓手"
  },
  {
    "id": 179,
    "name": "锦帆游击",
    "orig": "精灵游击兵",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 5,
    "ability": "agile",
    "keyword": "伏击【精锐】",
    "rarity": "bronze",
    "filename": "锦帆游击"
  },
  {
    "id": 180,
    "name": "江东水军",
    "orig": "矮人战士",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "bronze",
    "filename": "江东水军"
  },
  {
    "id": 181,
    "name": "江东谋士",
    "orig": "精灵法师",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 5,
    "ability": "agile",
    "keyword": "伏击【辅助】",
    "rarity": "bronze",
    "filename": "江东谋士"
  },
  {
    "id": 182,
    "name": "东吴军医",
    "orig": "矮人医师",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "close",
    "strength": 4,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "bronze",
    "filename": "东吴军医"
  },
  {
    "id": 183,
    "name": "东吴楼船器械",
    "orig": "矮人投石机",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "东吴楼船器械"
  },
  {
    "id": 184,
    "name": "江东弩手",
    "orig": "多尔布雷坦纳弓箭手",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "江东弩手"
  },
  {
    "id": 185,
    "name": "江东游医",
    "orig": "私枭医生",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "medic",
    "keyword": "归阵【普通】",
    "rarity": "bronze",
    "filename": "江东游医"
  },
  {
    "id": 186,
    "name": "江东宿卫",
    "orig": "维里赫德旅老兵",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "close",
    "strength": 5,
    "ability": "morale",
    "keyword": "士气大振【精锐】",
    "rarity": "bronze",
    "filename": "江东宿卫"
  },
  {
    "id": 187,
    "name": "江东新兵",
    "orig": "维里赫德旅见习生",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 3,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "江东新兵"
  },
  {
    "id": 188,
    "name": "东吴水兵",
    "orig": "精灵战士",
    "faction": "东吴",
    "deck": "dongwu",
    "type": "铜卡",
    "row": "agile",
    "strength": 3,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "东吴水兵"
  },
  {
    "id": 189,
    "name": "黄巾流民",
    "orig": "腐食魔",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "",
    "keyword": "殉战【普通】",
    "rarity": "bronze",
    "filename": "黄巾流民"
  },
  {
    "id": 190,
    "name": "黄巾步兵",
    "orig": "食尸鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "muster",
    "keyword": "死士【普通】",
    "rarity": "bronze",
    "filename": "黄巾步兵"
  },
  {
    "id": 191,
    "name": "黄巾河兵",
    "orig": "水鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "agile",
    "strength": 2,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "黄巾河兵"
  },
  {
    "id": 192,
    "name": "黄巾哨探",
    "orig": "食腐鸟",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "agile",
    "strength": 1,
    "ability": "",
    "keyword": "无【普通】",
    "rarity": "bronze",
    "filename": "黄巾哨探"
  },
  {
    "id": 193,
    "name": "黄巾砦守",
    "orig": "石像鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "siege",
    "strength": 3,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "黄巾砦守"
  },
  {
    "id": 194,
    "name": "黄巾傀儡",
    "orig": "魔像",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "siege",
    "strength": 4,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "黄巾傀儡"
  },
  {
    "id": 195,
    "name": "黄巾斥侯",
    "orig": "妖鸟",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "agile",
    "strength": 2,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "黄巾斥侯"
  },
  {
    "id": 196,
    "name": "黄巾蛮夫",
    "orig": "巨食妖",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 5,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "bronze",
    "filename": "黄巾蛮夫"
  },
  {
    "id": 197,
    "name": "黄巾渠帅",
    "orig": "食尸鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "",
    "keyword": "殉战【精英】",
    "rarity": "bronze",
    "filename": "黄巾渠帅"
  },
  {
    "id": 198,
    "name": "黄巾水卒",
    "orig": "水鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "agile",
    "keyword": "伏击【普通】",
    "rarity": "bronze",
    "filename": "黄巾水卒"
  },
  {
    "id": 199,
    "name": "黄巾力士",
    "orig": "沼泽怪",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "bronze",
    "filename": "黄巾力士"
  },
  {
    "id": 200,
    "name": "黄巾死囚",
    "orig": "墓穴食尸妖",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 4,
    "ability": "",
    "keyword": "殉战【普通】",
    "rarity": "bronze",
    "filename": "黄巾死囚"
  },
  {
    "id": 201,
    "name": "黄巾巫祝",
    "orig": "吸血鬼：吸血女妖",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "ranged",
    "strength": 5,
    "ability": "muster",
    "keyword": "死士【辅助】",
    "rarity": "bronze",
    "filename": "黄巾巫祝"
  },
  {
    "id": 202,
    "name": "黄巾狂徒",
    "orig": "吸血鬼：蝠翼妖",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 4,
    "ability": "muster",
    "keyword": "聚将【普通】",
    "rarity": "bronze",
    "filename": "黄巾狂徒"
  },
  {
    "id": 203,
    "name": "黄巾悍匪",
    "orig": "吸血鬼：卡塔坎",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "bronze",
    "filename": "黄巾悍匪"
  },
  {
    "id": 204,
    "name": "黄巾游骑",
    "orig": "孽鬼",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "muster",
    "keyword": "聚将【普通】",
    "rarity": "bronze",
    "filename": "黄巾游骑"
  },
  {
    "id": 205,
    "name": "黄巾小帅",
    "orig": "孽鬼战士",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "muster",
    "keyword": "聚将【普通】",
    "rarity": "bronze",
    "filename": "黄巾小帅"
  },
  {
    "id": 206,
    "name": "黄巾山砦",
    "orig": "地元素",
    "faction": "黄巾",
    "deck": "huangjin",
    "type": "铜卡",
    "row": "siege",
    "strength": 5,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "黄巾山砦"
  },
  {
    "id": 207,
    "name": "南蛮狂战士",
    "orig": "狂战士",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "muster",
    "keyword": "死士【普通】",
    "rarity": "bronze",
    "filename": "南蛮勇士"
  },
  {
    "id": 208,
    "name": "南蛮部族兵",
    "orig": "盾女",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 3,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "bronze",
    "filename": "南蛮部族兵"
  },
  {
    "id": 209,
    "name": "南蛮弓手",
    "orig": "猎人",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "ranged",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "南蛮弓手"
  },
  {
    "id": 210,
    "name": "南蛮死士",
    "orig": "狂战士",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "bronze",
    "filename": "南蛮死士"
  },
  {
    "id": 211,
    "name": "南蛮蛮兵",
    "orig": "盾女",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 5,
    "ability": "",
    "keyword": "护甲【普通】",
    "rarity": "bronze",
    "filename": "南蛮蛮兵"
  },
  {
    "id": 212,
    "name": "羌胡猎手",
    "orig": "猎人",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "ranged",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "羌胡猎手"
  },
  {
    "id": 213,
    "name": "南蛮巫祝",
    "orig": "萨满",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "ranged",
    "strength": 4,
    "ability": "medic",
    "keyword": "归阵【辅助】",
    "rarity": "bronze",
    "filename": "南蛮巫祝"
  },
  {
    "id": 214,
    "name": "诸侯斥候",
    "orig": "史凯利格斥候",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "agile",
    "strength": 4,
    "ability": "",
    "keyword": "侦查【辅助】",
    "rarity": "bronze",
    "filename": "诸侯斥候"
  },
  {
    "id": 215,
    "name": "诸侯攻城冲车",
    "orig": "史凯利格投石机",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "siege",
    "strength": 7,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "诸侯攻城冲车"
  },
  {
    "id": 216,
    "name": "南蛮勇士",
    "orig": "安·克莱特家族战士",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【精英】",
    "rarity": "bronze",
    "filename": "南蛮勇士"
  },
  {
    "id": 217,
    "name": "羌弓手",
    "orig": "布罗克瓦家族弓箭手",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "ranged",
    "strength": 6,
    "ability": "",
    "keyword": "无【精英】",
    "rarity": "bronze",
    "filename": "羌弓手"
  },
  {
    "id": 218,
    "name": "蛮部劫掠者",
    "orig": "迪门家族海盗",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "agile",
    "strength": 5,
    "ability": "",
    "keyword": "殉战【普通】",
    "rarity": "bronze",
    "filename": "蛮部劫掠者"
  },
  {
    "id": 219,
    "name": "南蛮盾卫",
    "orig": "德拉蒙家族盾女",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【精英】",
    "rarity": "bronze",
    "filename": "南蛮盾卫"
  },
  {
    "id": 220,
    "name": "诸侯说客",
    "orig": "海梅家族吟游诗人",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "ranged",
    "strength": 4,
    "ability": "morale",
    "keyword": "士气大振【辅助】",
    "rarity": "bronze",
    "filename": "诸侯说客"
  },
  {
    "id": 221,
    "name": "诸侯工匠",
    "orig": "托达罗赫家族军械师",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "siege",
    "strength": 4,
    "ability": "",
    "keyword": "无【器械】",
    "rarity": "bronze",
    "filename": "诸侯工匠"
  },
  {
    "id": 222,
    "name": "蛮部快船",
    "orig": "轻型大艇",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "agile",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【器械】",
    "rarity": "bronze",
    "filename": "蛮部快船"
  },
  {
    "id": 223,
    "name": "蛮部战舰",
    "orig": "战型大艇",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "agile",
    "strength": 6,
    "ability": "bond",
    "keyword": "同袍呼应【器械】",
    "rarity": "bronze",
    "filename": "蛮部战舰"
  },
  {
    "id": 224,
    "name": "南蛮少年死士",
    "orig": "年轻狂战士",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "muster",
    "keyword": "死士【精英】",
    "rarity": "bronze",
    "filename": "南蛮少年死士"
  },
  {
    "id": 225,
    "name": "南蛮祭器",
    "orig": "坎毕",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 0,
    "ability": "",
    "keyword": "殉战【特殊】",
    "rarity": "bronze",
    "filename": "南蛮祭器"
  },
  {
    "id": 226,
    "name": "西凉铁骑",
    "orig": "狂战士",
    "faction": "群雄(DLC)",
    "deck": "qunxiong",
    "type": "铜卡",
    "row": "close",
    "strength": 5,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "bronze",
    "filename": "西凉铁骑"
  },
  {
    "id": 227,
    "name": "汉室流民",
    "orig": "农民",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 1,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "汉室流民"
  },
  {
    "id": 228,
    "name": "汉室民兵",
    "orig": "民兵",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "汉室民兵"
  },
  {
    "id": 229,
    "name": "郭汜",
    "orig": "汉廷弓箭手",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "ranged",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【董卓部将】祸乱京师",
    "rarity": "bronze",
    "filename": "郭汜"
  },
  {
    "id": 230,
    "name": "朝廷探骑",
    "orig": "汉廷斥候",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "agile",
    "strength": 2,
    "ability": "",
    "keyword": "侦查【普通】",
    "rarity": "bronze",
    "filename": "朝廷探骑"
  },
  {
    "id": 231,
    "name": "洛阳流民",
    "orig": "农民",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 1,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "洛阳流民"
  },
  {
    "id": 232,
    "name": "长安民兵",
    "orig": "民兵",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 2,
    "ability": "bond",
    "keyword": "同袍呼应【普通】",
    "rarity": "bronze",
    "filename": "长安民兵"
  },
  {
    "id": 233,
    "name": "羽林弓手",
    "orig": "汉廷弓箭手",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "ranged",
    "strength": 3,
    "ability": "bond",
    "keyword": "同袍呼应【精锐】",
    "rarity": "bronze",
    "filename": "羽林弓手"
  },
  {
    "id": 234,
    "name": "缇骑",
    "orig": "汉廷斥候",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "agile",
    "strength": 3,
    "ability": "",
    "keyword": "侦查【精锐】",
    "rarity": "bronze",
    "filename": "缇骑"
  },
  {
    "id": 235,
    "name": "汉献帝",
    "orig": "独角兽",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "ranged",
    "strength": 5,
    "ability": "purify",
    "keyword": "净化【特殊】",
    "rarity": "bronze",
    "filename": "汉献帝"
  },
  {
    "id": 236,
    "name": "华佗",
    "orig": "老巫妪",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "ranged",
    "strength": 10,
    "ability": "medic",
    "keyword": "归阵【神医】",
    "rarity": "bronze",
    "filename": "华佗"
  },
  {
    "id": 237,
    "name": "牛来",
    "orig": "牛",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 1,
    "ability": "",
    "keyword": "无【梗】电影《牛来》",
    "rarity": "bronze",
    "filename": "牛来"
  },
  {
    "id": 238,
    "name": "李傕",
    "orig": "欧吉尔德",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 8,
    "ability": "hero",
    "keyword": "猛将【董卓部将】反攻长安",
    "rarity": "bronze",
    "filename": "李傕"
  },
  {
    "id": 239,
    "name": "幻术黑影",
    "orig": "刚特·欧迪姆黑暗",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "ranged",
    "strength": 0,
    "ability": "purify",
    "keyword": "净化【特殊】",
    "rarity": "bronze",
    "filename": "幻术黑影"
  },
  {
    "id": 240,
    "name": "郝萌",
    "orig": "维瑟米尔",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 8,
    "ability": "hero",
    "keyword": "猛将【吕布八健将】",
    "rarity": "bronze",
    "filename": "郝萌"
  },
  {
    "id": 241,
    "name": "侯成",
    "orig": "狮鹫",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 7,
    "ability": "hero",
    "keyword": "猛将、灵活【吕布八健将】",
    "rarity": "bronze",
    "filename": "侯成"
  },
  {
    "id": 242,
    "name": "成廉",
    "orig": "约翰·纳塔利斯",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 7,
    "ability": "hero",
    "keyword": "猛将、灵活【吕布八健将】",
    "rarity": "bronze",
    "filename": "成廉"
  },
  {
    "id": 243,
    "name": "魏续",
    "orig": "弗农·罗契",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "hero",
    "keyword": "猛将【吕布八健将】",
    "rarity": "bronze",
    "filename": "魏续"
  },
  {
    "id": 244,
    "name": "宋宪",
    "orig": "伊斯特拉德·帝森",
    "faction": "汉廷中立",
    "deck": "hanting",
    "type": "铜卡",
    "row": "close",
    "strength": 6,
    "ability": "hero",
    "keyword": "猛将【吕布八健将】",
    "rarity": "bronze",
    "filename": "宋宪"
  },
  {
    "id": 245,
    "name": "战鼓",
    "orig": "Commander's Horn",
    "faction": "特殊",
    "deck": "special",
    "type": "特殊牌",
    "row": "",
    "strength": 0,
    "ability": "horn",
    "keyword": "计谋：本排非猛将战力×2",
    "rarity": "special",
    "filename": "战鼓"
  },
  {
    "id": 246,
    "name": "招降",
    "orig": "Bait",
    "faction": "特殊",
    "deck": "special",
    "type": "特殊牌",
    "row": "",
    "strength": 0,
    "ability": "decoy",
    "keyword": "计谋：回收场上非猛将回手牌",
    "rarity": "special",
    "filename": "招降"
  },
  {
    "id": 247,
    "name": "烽火燎原",
    "orig": "Scorch",
    "faction": "特殊",
    "deck": "special",
    "type": "特殊牌",
    "row": "",
    "strength": 0,
    "ability": "scorch",
    "keyword": "计谋：排内敌方≥10清最高非猛将",
    "rarity": "special",
    "filename": "烽火燎原"
  },
  {
    "id": 248,
    "name": "寒潮",
    "orig": "Frost",
    "faction": "特殊",
    "deck": "weather",
    "type": "特殊牌",
    "row": "weather",
    "strength": 0,
    "ability": "frost",
    "keyword": "天气：近战普通单位强制战力1",
    "rarity": "special",
    "filename": "寒潮"
  },
  {
    "id": 249,
    "name": "大雾",
    "orig": "Fog",
    "faction": "特殊",
    "deck": "weather",
    "type": "特殊牌",
    "row": "weather",
    "strength": 0,
    "ability": "fog",
    "keyword": "天气：弓箭手普通单位强制战力1",
    "rarity": "special",
    "filename": "大雾"
  },
  {
    "id": 250,
    "name": "暴雨",
    "orig": "Rain",
    "faction": "特殊",
    "deck": "weather",
    "type": "特殊牌",
    "row": "weather",
    "strength": 0,
    "ability": "rain",
    "keyword": "天气：器械普通单位强制战力1",
    "rarity": "special",
    "filename": "暴雨"
  },
  {
    "id": 251,
    "name": "放晴",
    "orig": "Clear Weather",
    "faction": "特殊",
    "deck": "weather",
    "type": "特殊牌",
    "row": "weather",
    "strength": 0,
    "ability": "clear",
    "keyword": "计谋：清除全部天气",
    "rarity": "special",
    "filename": "放晴"
  },
  {
    "id": 252,
    "name": "海上狂风",
    "orig": "Skellige Storm",
    "faction": "特殊",
    "deck": "weather",
    "type": "特殊牌",
    "row": "weather",
    "strength": 0,
    "ability": "skellestorm",
    "keyword": "天气：群雄DLC专属，弓箭手+器械普通置1",
    "rarity": "special",
    "filename": "海上狂风"
  },
  {
    "id": 253,
    "name": "蛮巫祭礼",
    "orig": "Mardroeme",
    "faction": "特殊",
    "deck": "special",
    "type": "特殊牌",
    "row": "",
    "strength": 0,
    "ability": "mardroeme",
    "keyword": "计谋：本排死士全部变身高战力",
    "rarity": "special",
    "filename": "蛮巫祭礼"
  },
  {
    "id": 254,
    "name": "伪令",
    "orig": "Decoy",
    "faction": "特殊",
    "deck": "special",
    "type": "特殊牌",
    "row": "",
    "strength": 0,
    "ability": "decoy",
    "keyword": "计谋：同招降效果",
    "rarity": "special",
    "filename": "伪令"
  }
];

// 阵营中文名映射
var FACTION_ZH = {
  shuhan: '蜀汉', caowei: '曹魏', dongwu: '东吴', huangjin: '黄巾', qunxiong: '群雄', hanting: '汉廷中立', special: '特殊', weather: '天气', leader: '领袖'
};
